# Generated by Django 2.2.2 on 2019-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0003_auto_20190821_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonparagraph',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
