# Generated by Django 2.2.2 on 2019-08-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0004_lessonparagraph_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('instruction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instruction_name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
            },
        ),
        migrations.AddField(
            model_name='lessonnavigation',
            name='associatedParagraph',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InstructionParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('ordering', models.IntegerField(default=0)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mips.Instruction')),
            ],
            options={
                'verbose_name': 'Instruction Paragraph',
                'verbose_name_plural': 'Instruction Paragraphs',
            },
        ),
        migrations.CreateModel(
            name='InstructionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=150)),
                ('ordering', models.IntegerField(default=0)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mips.Instruction')),
            ],
            options={
                'verbose_name': 'Instruction Image',
                'verbose_name_plural': 'Instruction Images',
            },
        ),
    ]
