# Generated by Django 2.2.2 on 2019-08-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0006_auto_20190821_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonnavigation',
            old_name='associatedParagraph',
            new_name='lessonParagraph',
        ),
    ]
