# Generated by Django 2.2.2 on 2019-08-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0008_auto_20190821_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonnavigation',
            name='lessonParagraph',
        ),
    ]
