# Generated by Django 2.2.2 on 2019-08-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0009_remove_lessonnavigation_lessonparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnavigation',
            name='lessonParagraph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mips.LessonParagraph'),
        ),
    ]
