# Generated by Django 2.2.2 on 2019-08-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0011_auto_20190822_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonParagaphImage',
            new_name='LessonParagraphImage',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
