# Generated by Django 2.2.2 on 2019-08-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0013_auto_20190827_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='associated_file',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
