# Generated by Django 2.2.2 on 2019-09-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0014_lesson_associated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionparagraph',
            name='paragraph_type',
            field=models.CharField(choices=[('Preface', 'Preface'), ('Syntax', 'Syntax'), ('Example', 'Example')], default='Preface', max_length=50),
        ),
    ]
