# Generated by Django 2.2.2 on 2019-09-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0015_instructionparagraph_paragraph_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionparagraph',
            name='paragraph_type',
            field=models.CharField(choices=[('Preface', 'Preface'), ('Syntax', 'Syntax'), ('Example', 'Example'), ('Result', 'Result')], default='Preface', max_length=50),
        ),
    ]
